# Generated by Django 4.2.7 on 2023-11-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
