# Generated by Django 4.2.7 on 2023-11-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_enquiry_subject_alter_enquiry_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.IntegerField(max_length=10),
        ),
    ]
