# Generated by Django 4.2.7 on 2023-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_enquiry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='comment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
