# Generated by Django 4.2.7 on 2023-12-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_enquiry_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.BigIntegerField(max_length=11),
        ),
    ]
